/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bn_sample14_1_GL2JNILib */

#ifndef _Included_com_bn_sample14_1_GL2JNILib
#define _Included_com_bn_sample14_1_GL2JNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bn_sample14_1_GL2JNILib
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_bn_sample14_11_GL2JNILib_init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_bn_sample14_1_GL2JNILib
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bn_sample14_11_GL2JNILib_step
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
