/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bn_sample14_2_GL2JNILib */

#ifndef _Included_com_bn_sample14_2_GL2JNILib
#define _Included_com_bn_sample14_2_GL2JNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bn_sample14_2_GL2JNILib
 * Method:    init
 * Signature: (Landroid/opengl/GLSurfaceView;II)V
 */
JNIEXPORT void JNICALL Java_com_bn_sample14_12_GL2JNILib_init
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     com_bn_sample14_2_GL2JNILib
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bn_sample14_12_GL2JNILib_step
  (JNIEnv *, jclass);

/*
 * Class:     com_bn_sample14_2_GL2JNILib
 * Method:    setCamera
 * Signature: (FFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_bn_sample14_12_GL2JNILib_setCamera
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
